### ISSUE TITLE
Latest release 3.3.1 fails to deploy to pypi

### ISSUE THREAD

**Issue by belugame** [James1345/django-rest-knox#107]
see job log: https://travis-ci.org/James1345/django-rest-knox/jobs/409780228

HTTPError: 400 Client Error: User 'xxx.xxx' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information. for url: https://upload.pypi.org/legacy/

Original author was informed by me.

**Comment by belugame** [comment]
ping @James1345

**Comment by belugame** [comment]
Feel free to drop him an email, you can find it here:
https://github.com/James1345/django-rest-knox/blob/master/setup.py#L28

**Comment by rphlo** [comment]
Thing is he should have already received multiple email regarding this issue and did not respond to any of those (Pypi email confirmation, Github notifications...)

**Comment by belugame** [comment]
he does reply to personal emails relatively quick. People tend to filter away auto-emails into folders. At least I do :)

**Comment by rphlo** [comment]
I sent an email.

**Comment by rphlo** [comment]
@James1345 replied 

> PyPi seem to have changed something and I can't get back into my old account. I don't know why yet, but it seems to have completely lost my email address as one that's registered to an account. 
>
> I'm contacting PyPi support to see if I can get back into the account

**Comment by James1345** [comment]
Okay, email address verified, the builds should succeed now hopefully

**Comment by rphlo** [comment]
Travis build went through but show `Skipping a deployment with the pypi provider because this is not a tagged commit`

**Comment by James1345** [comment]
Good spot. Need to force it to try a pypi deployment somehow...

**Comment by belugame** [comment]
@James1345  any update on this?

**Comment by luk156** [comment]
ping

**Comment by James1345** [comment]
next release should force a deployment

**Comment by belugame** [comment]
just tagged master as 3.3.1, hopefully already on its way to pypi

**Comment by belugame** [comment]
Release failed :( @James1345 

```
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
django_rest_knox.egg-info/PKG-INFO already exists, no checkout
django_rest_knox.egg-info/SOURCES.txt already exists, no checkout
django_rest_knox.egg-info/dependency_links.txt already exists, no checkout
django_rest_knox.egg-info/requires.txt already exists, no checkout
django_rest_knox.egg-info/top_level.txt already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy

```

https://travis-ci.org/James1345/django-rest-knox/jobs/434573815

**Comment by rphlo** [comment]
@James1345 did you forget to update your password in `.travis.yml` after you recovered your account?

**Comment by James1345** [comment]
That's not impossible

**Comment by johnraz** [comment]
Hey guys,

Would be nice to merge #109 with a successful pypi release 🎉 

@James1345 would you have a bit of time to create a PR with the updated credentials?

Cheers 🤓

**Comment by belugame** [comment]
ping @James1345

**Comment by James1345** [comment]
I'll give it a poke this evening

**Comment by johnraz** [comment]
@James1345 any chance we could see this moving forward or maybe you can delegate some permissions to @belugame ?

**Comment by belugame** [comment]
:exclamation:  We are unable to release since almost 3 months now, @James1345 
At the moment the project sees a lot of valuable contributions from motivated coders new to the project, far more than in the past. It's a shame that we cannot thank them with regular releases to pypi. If you can't find the time for reestablishing the release workflow, I guess we have to republish it under a new name sadly. :-/

**Comment by James1345** [comment]
I did the thing. Is it still not working?

**Comment by belugame** [comment]
Oh I wasn't aware you did. Just made a new release. It failed sadly:

https://travis-ci.org/James1345/django-rest-knox/jobs/445302892


```
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
django_rest_knox.egg-info/PKG-INFO already exists, no checkout
django_rest_knox.egg-info/SOURCES.txt already exists, no checkout
django_rest_knox.egg-info/dependency_links.txt already exists, no checkout
django_rest_knox.egg-info/requires.txt already exists, no checkout
django_rest_knox.egg-info/top_level.txt already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
```

**Comment by James1345** [comment]
On it right now, just reminding myself how travis works

**Comment by James1345** [comment]
Okay, I've re-reset the password. I'm doing a new release to try to make it deploy

**Comment by James1345** [comment]
@belugame it successfully deployed the first build, but then the others fail when it tries to deploy again with the other django versions... not sure of the solution yet

**Comment by James1345** [comment]
https://travis-ci.org/James1345/django-rest-knox/builds/445317311

**Comment by James1345** [comment]
Fixing it now with build stages

**Comment by James1345** [comment]
Going to leave it for tonight. It looks odd, but the deployment at least succeeds. I'll properly secure another new password some other day (leave this issue open so I remember)

**Comment by James1345** [comment]
It worked for the 2.7 config. The issue is that each config in the test
matrix is trying to deploy, which causes the file conflict.

Because we build a universal package, it should be fine to install 3.4.0
from pypi, we're just going to get this error every time we try to deploy

**Comment by johnraz** [comment]
This is precisely what I'm stating, yes.

**Comment by johnraz** [comment]
Created #138 to follow up on this, that way we can close this as the main issue is fixed.

**Comment by belugame** [comment]
thank you @johnraz
