### ISSUE TITLE
[Discussion/Suggestion] Ability to limit the amount of active tokens per user

### ISSUE THREAD

**Issue by sphrak** [James1345/django-rest-knox#108]
Hello,
Im testing out this library and so far I am really liking it, but I wonder if there is a way to throttle or limit the amount of keys a user can have?

I am willing to take a stab at this if it does not exist, but im curious to hear what everyone else thinks about it?

EDIT: I think that probably a limit is the way to go rather than throttling the requests since that can be handled by the throttling mechanism already built into DRF.

Kindly,
Sphrak

**Comment by rphlo** [comment]
Not sure what would be the use case for this but I would go by overriding the LoginView

```
class TokenLimitingLoginView(LoginView):
    max_token_count_per_user = 10
    def post(self, request, format=None):
        user_token_count = request.user.auth_token_set.all().count()
        if user_token_count >= self.max_token_count_per_user:
            return Response(
                {'error': 'User has reached max number of token per user'},
                status=status.HTTP_401_UNAUTHORIZED
            )
        super().post(request, format)
```

**Comment by belugame** [comment]
@sphrak thank your for your feature suggestion.

FYI We do clean up expired tokens here https://github.com/James1345/django-rest-knox/blob/5ace943e46c799da5c9eeb2e65336d88e63ca008/knox/auth.py#L103

You are right that it does not stop users from creating a large number of tokens. For most usecases a small number of tokens (if not 1 per user) would suffice. So I am not against implementing such limit which one can override per setting.

Please remember to also cover it with unit testing when you want to have a go at it.

**Comment by sphrak** [comment]
I close this issue since this has been accepted and now only merge into master is left. Discussion continues in PR if needed.
