### ISSUE TITLE
Emit a (django) signal when a token is removed

### ISSUE THREAD

**Issue by davidp94** [James1345/django-rest-knox#117]
I would like to implement logging when an authentication token is removed via the function `_cleanup_token`

It could be nice if the module would emit some different signals for the following items:
https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L101
and 
https://github.com/James1345/django-rest-knox/blob/master/knox/auth.py#L104

Documentation on signals:
https://docs.djangoproject.com/en/2.1/topics/signals/

**Comment by James1345** [comment]
Feature merged into develop (I don't actually know how to drive github to link this to the commit properly...)

**Comment by sphrak** [comment]
@James1345 you can reference the issue or PR in the commit message by hashtag numer like this: #117

**Comment by belugame** [comment]
closed in v3.3.1
