### ISSUE TITLE
Make MIN_REFRESH_INTERVAL a configurable settings

### ISSUE THREAD

**Issue by johnraz** [James1345/django-rest-knox#120]
I'd like to change and make the following a configurable settings:

https://github.com/James1345/django-rest-knox/blob/370b517a20429e1cccd7b8f8bbcce10c93b766e7/knox/settings.py#L40

@rphlo, @belugame  what's your opinion as you wrote / reviewed this part?

**Comment by belugame** [comment]
sure, go for it :+1:
