### ISSUE TITLE
Use only markdown

### ISSUE THREAD

**Issue by johnraz** [James1345/django-rest-knox#124]
I think it's a bit sad to have to switch between RST and MD syntax in the changelog / readme and the doc.

Would you mind if I rewrite everything in markdown instead?

**Comment by belugame** [comment]
totally agree, I think it stems from github/pypi not using the same format. If that's no longer the case and we can use either format for both, go for it!

**Comment by johnraz** [comment]
PR submitted.

**Comment by belugame** [comment]
closed in develop
