### ISSUE TITLE
Add Remember me option

### ISSUE THREAD

**Issue by rammanoj** [James1345/django-rest-knox#144]
I am not sure if this feature is already implemented. I am trying to set a time limit of 1 day for normal logins and for those who tick remember me, I want to set it to 1 month. In settings.py I declared globally 

` REST_KNOX = {
    'TOKEN_TTL': timedelta(hours=24),
}`

But I want to delcare it in my LoginView. I tried sending the `token_ttl` value to the parent pose method in form of kwargs. But It wasn't a successful attempt. So, asking here is there any way to implement it ??

**Comment by belugame** [comment]
I would try following. Override the LoginView.post in a new class in your code, call super() to get the token and then based on request.POST.get("remember_me") you can update the expiry of the token.
Then return the Response unchanged.

**Comment by rammanoj** [comment]
Thanks, @belugame, for the reply.  Is there any way to get the current AuthToken (when the user has logged in multiple systems) in serializers??.

**Comment by rammanoj** [comment]
@belugame how do I get the Authtoken modal object using the token (as the token is hashed, and which field of the table should I query ??)

**Comment by johnraz** [comment]
@rammanoj you can find the object by doing something like this (I tried it in a django shell and it worked): 

```
from knox.settings import CONSTANTS
user = User.objects.first()
token = AuthToken.objects.create(user=user)
AuthToken.objects.get(user=user, token_key=token[:CONSTANTS.TOKEN_KEY_LENGTH])
```

I found the answer by looking at the model manager's create method:

https://github.com/James1345/django-rest-knox/blob/517b6aad3db80684b6b56f6f8c4647e639a60731/knox/models.py#L20-L24

The problem with this approach is that you'll need to query the DB one more time to fetch back the object...

We could improve the `LoginView`'s code and have a hook method for the token creation:

https://github.com/James1345/django-rest-knox/blob/517b6aad3db80684b6b56f6f8c4647e639a60731/knox/views.py#L28

should be move to a `create_token()` method on the `LoginView` class to look like:

```
self.create_token(request)
```

That way one could easily extend the `LoginView` class and override the `create_token` method with custom logic.

But I'm not sure we want to add that kind of complexity to the `LoginView`...

**Comment by belugame** [comment]
I m all for making the view more flexible, cause I remember this has been a limit for more than one user by now :)
