### ISSUE TITLE
CHANGELOG.md should be the source of truth

### ISSUE THREAD

**Issue by johnraz** [James1345/django-rest-knox#148]
We should setup something so that `CHANGELOG.md` is used in the doc and as a source for github releases.

**Comment by sphrak** [comment]
Just my two cents, I support this and I think we should conform to follow this pattern: http://keepachangelog.com/en/1.0.0/ because its just so simple to use and follow :sunglasses:

**Comment by James1345** [comment]
That looks good

**Comment by johnraz** [comment]
I opened #161 to follow up on making the changelog's content better by complying to http://keepachangelog.com/en/1.0.0/.
