### ISSUE TITLE
django-rest-knox always response HTTP 401

### ISSUE THREAD

**Issue by ejoinel** [James1345/django-rest-knox#15]
hello, i am a newbie in django. I want to **django-rest-knox** authentication in my REST API, it's better than simple simple DRF Tokens .

I try to authenticate first created user : 

> curl -X POST -d "email=ejoinel@yahoo.fr&password=bejoilty" http://localhost:8000/api/auth/login/

But i always receive HTTP 401 error
I tried several solutions , but nothing works.
My settings:

![capture d ecran 2016-04-05 a 01 10 50](https://cloud.githubusercontent.com/assets/8337279/14266893/f3a66034-facb-11e5-86a7-a575bf660c1b.png)

![capture d ecran 2016-04-05 a 01 11 06](https://cloud.githubusercontent.com/assets/8337279/14266906/065adf0c-facc-11e5-94a2-d7c49c0dd8e9.png)

My user model inherited **AbstractBaseUser**

My model

![capture d ecran 2016-04-05 a 01 09 18](https://cloud.githubusercontent.com/assets/8337279/14266930/50b932ba-facc-11e5-8bfc-c2ded91a994a.png)

My UserSerializer

![capture d ecran 2016-04-05 a 01 10 06](https://cloud.githubusercontent.com/assets/8337279/14266938/67d7297a-facc-11e5-88db-dc9d3d021e0b.png)

Can someone tell me where is my mistake, please.

**Comment by James1345** [comment]
The problem is in your parameters for cURL. You've used -d, which sends the data up as form data. However, the authentication scheme is Basic Auth; so you need to use that.
This is built into cURL, try this:

`curl -X POST -u ejoinel@yahoo.:bejoilty http://localhost:8000/api/auth/login/`

**Comment by ejoinel** [comment]
thank you. I try it now

**Comment by ejoinel** [comment]
@James1345 , thank you for your help. Every views work. I just change fields in UserSerializer like 
`fields = ('email', 'first_name', 'last_name',)`.

thank you for everything
