### ISSUE TITLE
Is it possible extend tokens with extra data like last used IP, browser etc.?

### ISSUE THREAD

**Issue by PeterSR** [James1345/django-rest-knox#164]
In my project, I would like to extend the auth tokens with useful information about the user to allow them to see where they are logged in. Is this possible right now?

Is it simply a matter of extending AuthToken with custom fields, extending TokenAuthenticator with MyAuthToken as model and then using MyTokenAuthenticator in settings.py.
Is there a better way?

I am not sure if this is related to #159.

**Comment by johnraz** [comment]
Hi @PeterSR,
I think this is indeed related to #159 and this make a good use case to think about what exactly should be done there.
I definitely think it should be part of it.

I suggest we close this and keep the discussion going in #159.
/cc @belugame

**Comment by PeterSR** [comment]
Agreed. Closing.
