### ISSUE TITLE
When do you merge develop with master?

### ISSUE THREAD

**Issue by bobo-le** [James1345/django-rest-knox#167]
Hey, i need the fix with token.expires in auth.py.
When will you merge it into master?

**Comment by belugame** [comment]
just did it :)

**Comment by bobo-le** [comment]
@belugame thank you!

**Comment by bobo-le** [comment]
@belugame i forgot, could you push it to pypi?

**Comment by johnraz** [comment]
@bobo-le we are currently discussing the release in #168 if you want to follow along.
