### ISSUE TITLE
Fully customisable LoginView response

### ISSUE THREAD

**Issue by josh-stableprice** [James1345/django-rest-knox#171]
Currently, you require a user to override the post method in the event we need to change the format of the full response from LoginView. 

I suggest instead taking a parameter for the full response serializer `KNOX_LOGIN_RESPONSE_SERIALIZER`, with a method for us to override to provide context, with the token included. `def get_response_context(self, token)`

**Comment by johnraz** [comment]
Hi @josh-stableprice,

I'm very late on the ball here, sorry for not giving you some feedback.

I think you raise a very valid point and I've been thinking about this for quite a while as well.

The way I would approach this would be to provide a utility method that is passed the `token`, `AuthToken` instance, and request.

Basically this all code https://github.com/James1345/django-rest-knox/blob/05f218f1922999d1be76753076cf8af78f134e02/knox/views.py#L44-L55

Should be moved to a method that would look like 
```
def get_post_response(self, request, token, auth_token):
    UserSerializer = self.get_user_serializer_class() 
  
    data = { 
        'expiry': auth_token.expiry, 
        'token': token 
    } 
    if UserSerializer is not None: 
        data["user"] = UserSerializer( 
            request.user, 
            context=self.get_context() 
        ).data 
    return Response(data)
```

One could then simply override `get_post_response` to handle the returned payload as desired.

/cc @belugame @sphrak @James1345

**Comment by johnraz** [comment]
Reading my own message I think having a `get_post_response_data` method that returns the data dict would probably be better to override than a method that returns a full blown response.

**Comment by johnraz** [comment]
I believe we can assume this has been covered by #180 - please re-open if something is missing.
