### ISSUE TITLE
Object of type 'AuthToken' is not JSON serializable

### ISSUE THREAD

**Issue by kzrfaisal** [James1345/django-rest-knox#177]
I'm getting the above error when creating token, here's the code:

`
from rest_framework import generics, permissions
from rest_framework.response import Response
from knox.models import AuthToken
from .serializers import UserSerializer, RegisterSerializer

class RegisterAPI(generics.GenericAPIView):
    serializer_class = RegisterSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        return Response({
            "user": UserSerializer(user, context=self.get_serializer_context()).data,
            "token": AuthToken.objects.create(user)
        })
 `

what am I doing wrong here

**Comment by soulwawa** [comment]
I am wondering, too.

**Comment by johnraz** [comment]
ˋAuthToken.objects.create()ˋ returns a tuple of 2 values: the model instance and the token itself. See https://github.com/James1345/django-rest-knox/blob/05f218f1922999d1be76753076cf8af78f134e02/knox/models.py#L23. You need to only pass the token in your response.

**Comment by johnraz** [comment]
I'm going to close this as I believe my answer above fixes it, @kzrfaisal if something is still not right, feel free to re-open.

**Comment by radeshf** [comment]
one other way is use this 

`"token": AuthToken.objects.create(user)[1]`

**Comment by johnraz** [comment]
@radeshf: yes that would work but it's probably not how it would usually be done in Python, if you like conventions as I do 😉

**Comment by shawn-gosam** [comment]
Newbie here, I just wanna ask how would I be able to get just the expiry data? Thanks.

**Comment by boxabhi** [comment]
> `AuthToken.objects.create()` returns a tuple of 2 values: the model instance and the token itself. See
> 
> https://github.com/James1345/django-rest-knox/blob/05f218f1922999d1be76753076cf8af78f134e02/knox/models.py#L23
> 
> 
> You only need to pass the token in your response, not the all tuple.
> Something like this would do:
> 
> ```
>     ...
>     _, token = AuthToken.objects.create(user)
>     return Response({
>         "user": UserSerializer(user, context=self.get_serializer_context()).data,
>         "token": token
>     })
> ```

Not working

**Comment by caster8013** [comment]
> one other way is use this
> 
> `"token": AuthToken.objects.create(user)[1]`

Good, works for me!
