### ISSUE TITLE
Configure expiry serilializer

### ISSUE THREAD

**Issue by loicgasser** [James1345/django-rest-knox#178]
With the new release `4.0.x` we now return the `expiry` date which is great, but it cannot be formatted the way I want it to be without overloading the [post](https://github.com/James1345/django-rest-knox/blob/master/knox/views.py#L30) method of `LoginView`.

I would like to be able to return the `expiry` directly as a Unix Timestamp instead.
An easy way to achieve this goal could be to add a configurable expiry serializer, we could then import from `knox_settings`. (basically in the same fashion it has been done for `UserSerializer`.

I would be willing to provide such a patch if you guys agree with the idea.

**Comment by johnraz** [comment]
This seems like a valid proposal to me 👍🏻

**Comment by loicgasser** [comment]
ok cool I'll come up with a PR in the next days.

**Comment by loicgasser** [comment]
Done

**Comment by johnraz** [comment]
@loicgasser thanks for following this and cleaning things up, much appreciated 🙏
