### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by bymi15** [James1345/django-rest-knox#183]
> Line 64 in auth.py:

`token = token.decode("utf-8")`

I believe this line is not necessary in Python 3 and can be removed.
It also causes the above error in some cases.

**Comment by johnraz** [comment]
Hello, thanks for the report. Feel free to open a pull request and add the appropriate test case, should be an easy first contrib !

**Comment by bymi15** [comment]
Just figured it out!
`token` is a  token string encoded with: `encode(HTTP_HEADER_ENCODING)`
which makes line 64: `token = token.decode("utf-8")` necessary.

TLDR: No changes needed. False report.
