### ISSUE TITLE
TOKEN_LIMIT_PER_USER does not seem to be implemented

### ISSUE THREAD

**Issue by vaniatoperich** [James1345/django-rest-knox#197]
I am trying to limit the number of Token's issued per user, but it does not work (seems like it is not implemented at all?)

**Comment by johnraz** [comment]
the check is done here: https://github.com/James1345/django-rest-knox/blob/4e871880a3888a83f922ca5fdd13f5777f9e2423/knox/views.py#L57

it only checks non expired token btw.

**Comment by johnraz** [comment]
i’ll close, please reopen if something doesn’t work as expected
