### ISSUE TITLE
Add to django packages / rest framework docs

### ISSUE THREAD

**Issue by tomchristie** [James1345/django-rest-knox#2]
Looks good!

Want to consider adding to the rest framework grid on django packages: https://www.djangopackages.com/grids/g/django-rest-framework/

Also PR linking to this from the rest framework 'third party packages' docs in auth section would make sense.

Cheers!

**Comment by James1345** [comment]
third party package link PR sent.
Added to grid on django packages

**Comment by tomchristie** [comment]
Fab!
