### ISSUE TITLE
[Feature Suggestion] Add names to the knox tokens

### ISSUE THREAD

**Issue by Sveder** [James1345/django-rest-knox#209]
We've been happily using knox tokens, but our PMs wanted us to add token names. I've forked and added it (https://github.com/Sveder/django-rest-knox).
Wanted to see if there is interest to merge the changes back? Maybe add it as a separate NamedKnoxToken that can be interchangeable.
@James1345 wdyt?

**Comment by Sveder** [comment]
I'm going to ping a few of the recent committers too:
@johnraz @fgs-dbudwin @Rotzbua @belugame

**Comment by belugame** [comment]
hey  @Sveder, I m barely active in this project anymore. Could you explain the benefit of named tokens?

**Comment by Rotzbua** [comment]
Is it really required to change the library? Could you not solve it by inherit the knox class and add your custom name?

**Comment by Sveder** [comment]
@belugame Great question, I should've added it in the first post.
The main benefit is that users would like to name their tokens to remember what they are used for. For example one can be for a developer's machine, while another may be on a CI/CD machine. Sometimes you would like to be certain which one you are using / deleting / regenerating.
This is supported by quite a few services, for example in github you can name your access tokens (see "Note":
![image](https://user-images.githubusercontent.com/888366/101290276-d25b6c00-3809-11eb-8af8-4d41a5deb908.png)
)

@Rotzbua Great questions!
Is it really required to change the library? - It is not required, but it can be a great option for someone who has the same requirements as us. There are two +1s here so it seems like it is not just me.
Could you not solve it by inherit the knox class and add your custom name? - That is indeed a good solution, and that's what I'm suggesting to add. Of course, I can implement it for myself (and I did), but I think that adding it might help other people and save them the trouble of reimplementing this as knox saved me the trouble of implementing tokens.

If you think this is not a good fit, that's totally fine, feel free to close. If you think this can add value, I can work on a PR with unitests and docs and take it from there.

**Comment by johnraz** [comment]
I think this is indeed outside of the library's scope because as you said the requirement comes from the business, we should keep what's in this library as close as possible to the minimal technical use case.

I'm sure the need for a name in the token is most likely common, but as this is a small library with very few active maintainers, I think that limiting the scope of addition would serve the library better.

That's only my opinion though ;-)

**Comment by Sveder** [comment]
Ok, since this is not as well received as I hoped I'll close this ticket and instead update my fork. Thanks for your time guys!

**Comment by johnraz** [comment]
@Sveder thanks for your time and understanding 👍
