### ISSUE TITLE
Include cryptography in dependencies and drop PyOpenSSL

### ISSUE THREAD

**Issue by MarkusH** [James1345/django-rest-knox#22]
I see that knox uses PyOpenSSL to generate random numbers for the tokens. According to the [cryptography documentation](https://cryptography.io/en/latest/random-numbers/) using `os.urandom` is fine.

**Comment by James1345** [comment]
When this was first written, `os.urandom` was not recommended on all platforms: you'll notice it has been updated in newer versions of python. PyOpenSSL did what os.urandom now does - and called through to the correct randomness source - which it uses to seed its own PRNG.

I see no reason to change it. PyOpenSSL requires cryptography. PyOpenSSL's functionality that is used is `generate_bytes` - the name is clear, it works, change for change's own sake is a bad thing.
