### ISSUE TITLE
Invalid username/password with basic authentication shows browser basic auth dialog

### ISSUE THREAD

**Issue by akhayyat** [James1345/django-rest-knox#227]
Under the "Global usage on all views" section of the [Authentication documentation](https://james1345.github.io/django-rest-knox/auth/), the recommended approach to authenticate users before returning tokens to them is to use basic authentication for the login view:

```python
class LoginView(KnoxLoginView):
    authentication_classes = [BasicAuthentication]
```

This works well, except for one issue. When invalid username and password are submitted, the 401 response causes the browser to show the basic authentication dialog (due to the `WWW-Authenticate: Basic realm="api"` header in the response).

How can the basic authentication dialog be prevented from showing?

**Comment by johnraz** [comment]
This is how basic auth is meant to behave in the browser.

I think you may be able to override this behavior by using javascript on the client side, not 100% sure if the 401 would still be hijacked by the browser or not, bit it’s worth trying.

Also, I highly suggest you reconsider whether or not token authentication is the way to go in your web based application vs an usual session based authentication. It brings it’s lot of security issues as securely storing the token client side should be done in an appropriately secured https only cookie... also don’t forget that you need to protect your login form against CSRF in all cases.

I already argued in other issues why token auth is more meant to be used for server to server communication or mobile phone applications consuming the API (can’t look it up now as i’m on my phone) as the token is easier to secure there.

**Comment by akhayyat** [comment]
Thank you for the quick response, @johnraz, and for confirming the issue. I will look for ways to work around this, perhaps by sending another response, e.g. 400 instead of 401, or removing the `WWW-Authenticate` header from the login response.

I'm curious, though, about why you think session authentication is better than token authentication. If the client stores the token in in the browser's session storage or local storage, then CSRF is a non-issue (no cookies involved).

The main motivation for using token authentication in client-server communication is that it can be used as a single, universal authentication mechanism for web and mobile clients. It also allows for more decoupling of the client and the server. This is an API-only backend, BTW.

**Comment by akhayyat** [comment]
Here is a simple workaround based on this article:
http://loudvchar.blogspot.com/2010/11/avoiding-browser-popup-for-401.html

```python
from rest_framework.authentication import BasicAuthentication
from knox.views import LoginView as KnoxLoginView

class BasicLikeAuthentication(BasicAuthentication):
    def authenticate_header(self, request):
        return f'BasicLike realm="{self.www_authenticate_realm}"'

class LoginView(KnoxLoginView):
    authentication_classes = [BasicLikeAuthentication]
```

**Comment by johnraz** [comment]
storing the token in session storage / local storage is vulnerable to XSS not CSRF, this is a huge security flaw.

the login form itself is vulnerable to CSRF see https://stackoverflow.com/a/15350123

if you want to securely store a token in the browser you need to use http only cookie, this the only perfectly safe solution... and this is pretty much what session auth is already doing.

you are not coupling more client and server by using session auth... client and server need to know the authentication “key” in both session and token auth methods... the coupling is exactly the same.

as for having an universal authentication method for both web and mobile app, as it lowers security in the browser, I don’t think it brings value in the end.

and finally, the API-only argument is only related to how you present data to the user not how you handle authentication, you are (probably) using json and not HTML to render data but you are still using HTTP which allows session auth and is independent from the way you render data.

i know most resources online promote the use of token in modern js web app but if you dig a bit you’ll find that often there is a warning about security or that they don’t cover the token storage in the browser.

I hope its clearer ;-)

**Comment by johnraz** [comment]
I'm going to close this issue, @akhayyat feel free to re-open if needed.
