### ISSUE TITLE
Custom User Models with custom 'username' fields fail during serialization

### ISSUE THREAD

**Issue by davydany** [James1345/django-rest-knox#23]
When using knox, if I have a custom model that doesn't use `username` as the username field, like say `email_address`, the `UserSerializer` fails because Django lets us have custom username fields. (See: https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD)

**Comment by davydany** [comment]
I added the fix here: https://github.com/James1345/django-rest-knox/pull/24

**Comment by davydany** [comment]
The fix for this issue is here: https://github.com/James1345/django-rest-knox/pull/24 You closed it, without giving any feedback to it.

**Comment by belugame** [comment]
@davydany  sorry, this was my mistake. To follow the master-develop branch concept I rebased/merged the commit manually to develop and could not use your pull request. So this got a bit out of track. If there's a better way to handle it I'd be very happy to learn.

**Comment by belugame** [comment]
@davydany I noticed that one can change the base branch of an open pull request. Sorry again, will do that in the future.

**Comment by davydany** [comment]
:+1: Thank you!
