### ISSUE TITLE
Logout does not work well with Retrofit in Android

### ISSUE THREAD

**Issue by CelikAbdullah** [James1345/django-rest-knox#253]
hello, 

I use this library on my server but when I try to logout with an Android App as client, then I have some troubles handling the "204 no content" response returned by the LogoutView of this library. 
It is because Retrofit has problems with "204 no content" responses.

Is it possible for you to change the output of the LogoutView a little bit so that it returns a message containing sth. like {"response": "The logout was successful"} (with a HTTP status code of let's say 204) after a successful logout  ? That way the client would know that the logout request was successful.

**Comment by cosmosgenius** [comment]
you should use `Response<Void>` to handle 204 responses

**Comment by fmajestic** [comment]
I don't know about Android, but the above comment seems correct after a quick google search. I'll still write this for completeness.

The whole point of `204 No Content` is that the response doesn't contain any data. In fact, some browsers will refuse to read data from the response: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204. To return a message, make the code `200`.

The [default logout view](https://github.com/James1345/django-rest-knox/blob/develop/knox/views.py#L70) is very simple, you can define your own that has a different response:

```python
# views.py
class LogoutView(APIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def post(self, request, format=None):
        request._auth.delete()
        user_logged_out.send(sender=request.user.__class__, request=request, user=request.user)
        return Response({'response': 'Logged out successfully'})  # The only changed line
```

Then add it after importing all other knox urls:

```python
# urls.py
from django.urls import path, include
from .views import MyLogoutView

urlpatterns = [
    path('api/auth/', include('knox.urls')),
    path('api/auth/logout/', MyLogoutView.as_view())  # Overrides knox's logout view
]
```

**Comment by CelikAbdullah** [comment]
@fmajestic : Thank you but in the official documentation it says the following 

> Note It is not recommended to alter the Logout views. They are designed specifically for token management, and to respond to Knox authentication. Modified forms of the class may cause unpredictable results.

See here: https://james1345.github.io/django-rest-knox/views/

**Comment by CelikAbdullah** [comment]
@cosmosgenius : Yes, now I am using Response<Unit> to handle this.

With opening this thread, I just wanted to ask if the logout views could not return a simple response instead of returning 204 message. From an Android App perspective, a simple logout success response message is easier to handle since the body of the 204 response is null which leads to an additional if-else-statement.

**Comment by johnraz** [comment]
Looking at the exchange, I think the original question was properly answered and this can be closed 👍
