### ISSUE TITLE
create a release for django 4.0 compare

### ISSUE THREAD

**Issue by tr-conway** [James1345/django-rest-knox#260]
In `auth.py`

`from django.utils.translation import ugettext_lazy as _` no longer works as `ugettext_lazy` is removed.

`develop` branch seems to have solved this issue.

Can a release be created?

**Comment by Felix83000** [comment]
Same problem detected still on Django 4.0

**Comment by Felix83000** [comment]
If not fixed, I am affraid that django-rest-knox will not be usable at all on Django 4.0 ...

**Comment by jodusan** [comment]
Also The providing_args argument for django.dispatch.Signal is removed. in knox.singals.py 

Is django-rest-knox still maintained?

**Comment by PeterSR** [comment]
I am also interested in this release.

**Comment by mamtach** [comment]
https://github.com/James1345/django-rest-knox/issues/216

After upgrading python 3.8.1 to version 3.8.10, my project stopped working.
I am seeing following error

```
\lib\site-packages\knox\auth.py", line 11, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'
```

Pipfile:

```
django = ">=4.0"
djangorestframework = "~=3.13.1"
django-rest-knox = ">=4.1.0"
django-imagekit = ">=4.1.0"

[requires]
python_version = "3.8.10"
```

Please suggest me right versions so my project can be fixed.

**Comment by mamtach** [comment]
For now, I have downgraded django 4 to django 3 and it is working

**Comment by alex-pobeditel-2004** [comment]
@belugame @James1345  
Guys? Maybe somebody can create a release? :)

**Comment by belugame** [comment]
hey everyone,
I since a long time no longer have an eye on this project, nor James (for even more years). So I don't feel like the right person to make releases. I would recommend for any interested person to make a fork and release from there to a new pip project.

**Comment by johnraz** [comment]
Fully agree with @belugame here, it would even be better if @James1345  could hand-over the pypi name, or someone could claim the pypi name (https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer).

**Comment by Rotzbua** [comment]
Dirty fix is to simply pin to the latest commit:

> -e git+https://github.com/James1345/django-rest-knox.git@8447cd00358b1a3f76862278711abd2cdcb8837a#egg=django_rest_knox

**Comment by dethos** [comment]
> hey everyone,
> I since a long time no longer have an eye on this project, nor James (for even more years). So I don't feel like the right person to make releases. I would recommend for any interested person to make a fork and release from there to a new pip project.

I understand, it seems more and more likely that anyone wishing to upgrade to Django 4 will have to rely on a fork. However it would be nice that development would converge on a single fork.

> Fully agree with @belugame here, it would even be better if @James1345 could hand-over the pypi name, or someone could claim the pypi name (https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer).

This would be better indeed. 

Otherwise I suggest that some information should be added to the `README.md` file, stating that the project is not maintained anymore, since what was said [a few months ago, in another issue, is no longer true](https://github.com/James1345/django-rest-knox/issues/254#issuecomment-889159980):

> It's not actively developed for new features, but if there was a major issue it should get fixed also.

**Comment by James1345** [comment]
I'll get a release sorted soon

**Comment by James1345** [comment]
Hadn't realised no-one was watching this any more - sorry for the delay folks!

**Comment by Rotzbua** [comment]
@James1345 Created a pr #261 to test current python and django version which should help to maintain repo.

**Comment by NickWinston123** [comment]
Please implement this I want to use knox with 4.0 🙏

**Comment by Rotzbua** [comment]
@NickWinston123 You do not need a release. As I mentioned in https://github.com/James1345/django-rest-knox/issues/260#issuecomment-1011169192 you can use the latest version.

**Comment by NickWinston123** [comment]
> @NickWinston123 You do not need a release. As I mentioned in [#260 (comment)](https://github.com/James1345/django-rest-knox/issues/260#issuecomment-1011169192) you can use the latest version.

I am a noob and didn't know that was a pip command, thanks it is working now!

**Comment by Felix83000** [comment]
As said, it is a dirty fix... I hope a release will be uploaded to pypi

**Comment by James1345** [comment]
I'm going to get a release up on PyPI soon, I promise.

**Comment by jodusan** [comment]
@James1345 any ETA? Thanks!

**Comment by belugame** [comment]
I created a 4.2.0 release: https://github.com/James1345/django-rest-knox/releases/tag/4.2.0 for Django <=4

**Comment by Felix83000** [comment]
Great thank you! Will it be published on pypi.org?

**Comment by belugame** [comment]
Yes, I just did so :)
https://pypi.org/project/django-rest-knox/4.2.0/
