### ISSUE TITLE
How secure is having an 8-character AuthToken.token_key?

### ISSUE THREAD

**Issue by aaronn** [James1345/django-rest-knox#288]
I notice the AuthToken.token_key is only 8 characters long which is significantly shorter than something like DRF's own TokenAuthentication. 

Wouldn't this make it significantly easier to brute-force a user account?

**Comment by johnraz** [comment]
token_key is not the actual token, it’s a shortened version that can be used to filter out matching potential token before actually matching them against the digest. 

See https://github.com/James1345/django-rest-knox/blob/3a1bc584f9691f4bc19d8a04a98c68c293be9ca6/knox/auth.py#L64

**Comment by aaronn** [comment]
@johnraz I might be misunderstanding something here – I understand that the token_key is a shortened version of the digest, but since the token_key is what the client provides, what prevents an attacker from generating random 8-char long auth tokens and passing them in as bearer tokens until they get a right one?

**Comment by johnraz** [comment]
The client provides the full token which is shortened and used to filter out records in the database to get back the AuthToken objects matching the shortened token_key field.

We then loop over all those objects and compare their stored digest value against the digest value of the token provided by the client.

If the client only provide a shortened token and not the full token, it will never match the digest.
