### ISSUE TITLE
Is CSRF neccesary with django-rest-knox?

### ISSUE THREAD

**Issue by tim89643** [James1345/django-rest-knox#290]
Hi!

Is it correct that I can safely disable CSRF on all endpoints that are protected with django-rest-knox?

Looking into authentication methods and CSRF I learned:

*If authentication isn't automatic (typically provided by the browser) then you don't have to worry about CSRF protection. If your application is attaching the credentials via an Authorization header then the browser can't automatically authenticate the requests, and CSRF isn't possible.* ([source](https://security.stackexchange.com/questions/170388/do-i-need-csrf-token-if-im-using-bearer-jwt))

While this is talking about JWT-token, it also seems to apply to the bearer tokens that django-rest-knox uses (?)

I'm looking for some confirmation or counter points to my current understanding. All input is appreciated!

*Sidenote:*
I've currently disabled CSRF by setting django-drf `DEFAULT_AUTHENTICATION_CLASSES = knox.auth.TokenAuthentication`:

**Comment by johnraz** [comment]
If you are using it in the browser, you should store the token in a secret (http-safe) cookie which in turn requires csrf to be fully protected.

If you are using it in a server to server scenario, you don’t need csrf.

**Comment by tim89643** [comment]
Ok, that clears it up. Thank you
