### ISSUE TITLE
why not to add ttl for the tokens?

### ISSUE THREAD

**Issue by jerzyk** [James1345/django-rest-knox#3]
time to live, will allow to manage time limited sessions - will force to re-login user, with optional session extension will be a full end-to-end authentication

**Comment by James1345** [comment]
TTL is the very next feature I'm working on. Should be seeing it any time in the next few days ^_^

**Comment by James1345** [comment]
TTL is now present in the dev branch. next release will have it in

**Comment by muelli** [comment]
> with optional session extension

this seems to be missing though, right?  Right now the session is not extended after each request made.
