### ISSUE TITLE
Python 2.7 compatibility

### ISSUE THREAD

**Issue by hugozaggo** [James1345/django-rest-knox#4]
Hi. Great work!

In models.py , maybe change the following line:
        auth_token = super().create(digest=digest, salt=salt, user=user)
to:
        auth_token = super(AuthTokenManager,self).create(digest=digest, salt=salt, user=user)

for Python 2.7 compatibility?

**Comment by James1345** [comment]
Python 2.7 compatibility is not a priority for me. You are welcome to make the change and PR yourself, but I will not be spending any of my time on that currently.
