### ISSUE TITLE
Overriding KnoxLoginView for Global usage on all views

### ISSUE THREAD

**Issue by stantond** [James1345/django-rest-knox#40]
Does it make sense to make `authentication_classes = [BasicAuthentication]` the default behavior for `KnoxLoginView`? Or is it more common to require a different authentication method, rather than basic, for `KnoxLoginView`?

**Comment by belugame** [comment]
Not sure what is more common, I also use BasicAuthentication. But I would guess keeping knox use the DRF setting, results in less people needing to override the LoginView. There's e.g. OAuth2 and custom classes that people may use.

**Comment by belugame** [comment]
close due inactivity
