### ISSUE TITLE
Recommended TOKEN_TTL?

### ISSUE THREAD

**Issue by stantond** [James1345/django-rest-knox#42]
Unless I've confused myself, when a token has expired the client will need to login again to obtain a new token.

The default is 10 hours, but that seems very short given Knox could be providing tokens to mobile apps. Is there a reason to keep the TTL low?

It would be really helpful to add any clarification to the documentation!

**Comment by James1345** [comment]
While a client will have to reauthenticate, this doesn't necessarily mean the user will have to re-enter their credentials. In the example of o mobile app, the credentials might be stored on the device. The security implications of this are left up to the client app developer.

10 hours is the default, as it forces a client to reauth at least once in per working day, which seemed like a reasonable balance of security against convenience. However, like all settings you should consider whether the default is suitable. It is a default, not a recommendation.

For the documentation, I was thinking of writing a "Deploying" page, similar to Django's own ([here](https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/)), covering topics like TTL settings. This will certainly be going in it. (The things that seem obvious that people still ask questions about are the most important things to clearly document).

Thanks for your input
