### ISSUE TITLE
Better documentation regarding to how to use

### ISSUE THREAD

**Issue by kowsari** [James1345/django-rest-knox#47]
Hi
Thank you for this library as it seems it is a pretty good replacement for the basic token auth of DRF. I have been trying to get this library to work but confused as to how to actually replace the default token auth. 

I currently use djoser for REST register/login/logout/set password etc with basic DRF Token Auth

Is this is a replacement for the for...
1. Replace 
        'rest_framework.authentication.TokenAuthentication',
with
        'knox.auth.TokenAuthentication',

in
      'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),

or
2. Do I have to change my login/logout views in addition to changing the authentication.
3. Do I remove     'rest_framework.authtoken', from INSTALLED_APPS?

Thanks

**Comment by belugame** [comment]
Thank you for bringing this to our attention, I actually remember now that I missed this information as well when I first installed rest-knox. Can you check if these changes answer your questions:  https://github.com/James1345/django-rest-knox/pull/48

I however cannot comment on how/if the triangle of drf + knox + djoser plays together nicely. I have never used djoser. Your feedback would be valueable.

**Comment by kowsari** [comment]
Great! Thanks for the quick reply. This makes it more clear and will make it easier for somebody just getting started.

I played with trying to integrate djoser and rest-knox, but I couldnt get it to work yet. 

I am convinced there must be a way just to use the TokenAuthentication code of reset-knox with djoser as a replacement for the DRF TokenAuthentication. This will make it alot more useful since djoser has more APIs for managing registration/changing passwords as well as logging in/out.

**Comment by belugame** [comment]
fixed in #48
