### ISSUE TITLE
AuthTokenManager super() requires arguments in Python 2

### ISSUE THREAD

**Issue by bsteverink** [James1345/django-rest-knox#5]
this bit triggers a type error: "super() takes at least 1 argument (0 given)"

auth_token = super().create(digest=digest, salt=salt, user=user) 

I am using python 2.7.6 with django 1.8.2. 

I guess this would work as expected in Python 3.

**Comment by James1345** [comment]
I do not know if there are other issues that also prevent this from working in Python 2. I have no current  intention to spend any of my time supporting python 2. Anyone is welcome to support it if they have the time, I just don't.
