### ISSUE TITLE
Named tokens for server to server API?

### ISSUE THREAD

**Issue by jeffcjohnson** [James1345/django-rest-knox#50]
Would it make sense to add named tokens that do not expire so that they can be used in server to server communications?

**Comment by belugame** [comment]
A token that does not expire is like a password without username, no? Why not create a regular user account for those servers that use your api and authenticate them in with something other than rest-knox?

**Comment by jeffcjohnson** [comment]
I'm thinking of allowing a single user to create different keys for different uses.  The names would allow them to remember what they were used for a rotate as needed.  This seems to be a common use case.  Right now I'm telling users to use the API with Basic Auth over SSL and was hoping for something better.  Is there something for DRF that does this?

Something like Github access tokens (https://github.com/settings/tokens).

AWS AIM access keys are not named and I suppose Knox with non-expiring keys is pretty similar.

**Comment by etandel** [comment]
Maybe you could use something like OAuth?

**Comment by belugame** [comment]
close due inactivity
