### ISSUE TITLE
Need more information in setup knox docs

### ISSUE THREAD

**Issue by ishitap** [James1345/django-rest-knox#63]
In the [docs (Installation > Setup)](https://james1345.github.io/django-rest-knox/installation/#setup-knox), it says to "Make knox's TokenAuthentication your default authentification class for django-rest-framework." 

[Only way later in the docs](https://james1345.github.io/django-rest-knox/auth/) does it mention that doing so will require you to override the login view. 

It took me forever to figure out how I was getting a 401 even though I followed all the setup instructions. I think the information about overriding should be included in the setup, or there should be different setup instructions altogether so people can run a test quickly and make sure everything works post-install.

**Comment by belugame** [comment]
Yes, that should be included at least. Do you want to propose additional instructions that would have helped you?
