### ISSUE TITLE
OpenSSL.rand has been deprecated

### ISSUE THREAD

**Issue by AndreLobato** [James1345/django-rest-knox#68]
The module rand it's no longer supported in OpenSSL:

https://pypi.python.org/pypi/pyOpenSSL

This line breaks:

https://github.com/James1345/django-rest-knox/blob/master/knox/crypto.py#L5

**Comment by philngo** [comment]
Proposed a fix for this in #69

**Comment by belugame** [comment]
closed in #69, released in v 3.0.3
