### ISSUE TITLE
Why does LoginView use the IsAuthenticated permission class?

### ISSUE THREAD

**Issue by brmc** [James1345/django-rest-knox#7]
Is there something I'm missing?

**Comment by James1345** [comment]
The LoginView returns a LoginToken for a user that has authenticated using another authentication scheme (e.g. HttpBasic or Digest). You cannot (and wouldn't want to) return a token to an unauthenticated user.

To be clear, these are views for a RESTful API, LoginView is the view you would post to from the login page of a Single Page Application or a mobile app. It is not a traditional Django view (where the meaning would be to present the login page)

**Comment by bufke** [comment]
@James1345 what is your recommended way to authenticate? I saw you note that Basic Auth is bad in issue #1. Is there anything bad about initially using Basic Auth over https to get the token?

**Comment by James1345** [comment]
Currently the recommendation would be to use BasicAuth over HTTPS yes. It is less problematic when only used once this way. The token views should also only be transfered via HTTPS.
Using them this way is more secure than BasicAuth alone (which has several issues). I'm working towards some more Authentication schemes that should be even more secure, but I'm also trying not to add complexity (as that's when people start making errors that compromise security). So it's taking a while.
The tokens as they stand were born out of a lack of security/functionality of the default tokenauth system.
Hope this makes sense :)

**Comment by bufke** [comment]
Thanks that does make sense. Do you do consulting? I'm building a new open source project that will have some special requirements regarding authentication. If so email me at david at burkesoftware.com if you're interested.
