### ISSUE TITLE
OpnSSL ImportError: No module named rand

### ISSUE THREAD

**Issue by adriangaro** [James1345/django-rest-knox#73]
Using django-rest-knox==3.0.0 runs into 'ImportError: No module named rand'.

From what i have seen with the latest update of pyOpenSSL to 17.3.0 they might have removed the rand module. They recommend to use os.urandom instead.

**Comment by belugame** [comment]
You can upgrade to 3.0.3 now to fix that. It was released yesterday

**Comment by adriangaro** [comment]
Thanks!
