### ISSUE TITLE
Github Pages - Documentation - 404

### ISSUE THREAD

**Issue by dperconti** [James1345/django-rest-knox#80]
Just an FYI, the link to the documentation page is no longer found:
https://james1345.github.io/

**Comment by belugame** [comment]
@James1345, I may have broken that by removing the gh-pages branch, not knowing that it has a special purpose :-/ . I recreated the branch. Maybe the docs will show up again soonish or you need to revisit the settings. I don't have access to that.

**Comment by James1345** [comment]
Ah yes, the gh-pages branch is where github wiki lives.
I can restore it

**Comment by drd0013** [comment]
If people are looking for it and it's not back up yet, the wayback machine helped me. Not sure how up to date it is, but saved me from having to get the docs running myself.

https://web.archive.org/web/20171109103128/http://james1345.github.io/django-rest-knox/

**Comment by belugame** [comment]
@James1345 can you find the time to fix it? I try via "mkdocs gh-deploy" but it just stops after I enter my password without exiting or any further message.

**Comment by ksshetty** [comment]
@James1345 Can we please have the documentation restored? Not all the pages from the docs are available in the web archive. Thanks in advance

**Comment by belugame** [comment]
They are back online at https://james1345.github.io/django-rest-knox/
Thanks a lot to @James1345 due to work load he couldn't do it earlier. 

Sorry for the inconvenience, was my bad!

**Comment by ksshetty** [comment]
Thank you @James1345 and @belugame. Really appreciate it!
