### ISSUE TITLE
don't compare digests directly

### ISSUE THREAD

**Issue by fengsi** [James1345/django-rest-knox#83]
https://github.com/James1345/django-rest-knox/blob/e2c59581eac21381f9e789494744f20e4e187e7b/knox/auth.py#L71

it's bad to use `==` directly

https://docs.python.org/2/library/hmac.html#hmac.compare_digest

**Comment by belugame** [comment]
Thank you for the report! Would be a quick fix, are you keen to make a pull request, @fengsi?

**Comment by fengsi** [comment]
@belugame PR is up

**Comment by belugame** [comment]
closed in https://github.com/James1345/django-rest-knox/pull/84
