### ISSUE TITLE
Views do not have a serializer_class

### ISSUE THREAD

**Issue by jonpavelich** [James1345/django-rest-knox#94]
I am attempting to use django-rest-swagger for API documentation with DRF 3.8.1. Loading fails with the following exception:

```
'LoginView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
```

In the DRF documentation, it specifies that:
> `serializer_class` - [...] Typically, you must either set this attribute, or override the get_serializer_class() method.

http://www.django-rest-framework.org/api-guide/generic-views/#attributes

If I'm understanding the documentation correctly, it appears that DRF `GenericAPIView` must have a `serializer_class`, which `LoginView`, `LogoutView`, and `LogoutAllView` do not, so I believe this is a bug in django-rest-knox and not in django-rest-swagger. 

I'm going to override the classes in my project to add a `serializer_class`, but I think it might be a fairly involved set of changes. If you're interested in a pull request, please let me know and I can work on creating one once I make the changes.

**Comment by belugame** [comment]
You are right, but maybe it is easier than you expect. On a quick look we might simply be extending from the wrong DRF-class. There is a more basic view ApiView that we could inherit from than we do now. Maybe that already fixes what swagger chokes on.

We always welcome pull requests here, so let us know how you go :)

**Comment by jonpavelich** [comment]
You're right, subclassing `APIView` instead of `GenericAPIView` fixes this issue. Creating a PR now :)

**Comment by belugame** [comment]
Thank you for your work, @jonpavelich! :) 
I will make a bugfix release for it.

**Comment by opeeny** [comment]
I fail to understand the concern here, but i also have the similar problem, the question is how to go about it in the code 
AssertionError: 'LoginView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method
class LoginView(GenericAPIView):

    def post(self, request):
        data = request.data
        username = data.get('username', '')
        password = data.get('password', '')
        user = auth.authenticate(username=username, password=password)
        
        if user:
            auth_token = jwt.encode({'username': user.username}, settings.JWT_SECRET_KEY)
            serializer = UserSerializer(user)
             data = {'user': serializer.data, 'token': auth_token}
            return Response(data, status=status.HTTP_200_OK)
            #send user reponse
        return Response({'detail': 'Invalid credential'}, status=status.HTTP_401_UNAUTHORIZED)
Thanks

**Comment by belugame** [comment]
Is this your code that you posted, @opeeny? Try changing the class to "class LoginView(APIView):" and add a serializer_class attribute like you see in this snippet for example https://www.django-rest-framework.org/tutorial/3-class-based-views/#using-generic-class-based-views
